-- MIGRATION: Full Schema Sync
-- Run this in Supabase SQL Editor
CREATE TABLE IF NOT EXISTS public.quran_surahs (
    id INTEGER PRIMARY KEY,
    name_arabic TEXT NOT NULL,
    name_english TEXT NOT NULL,
    name_transliteration TEXT,
    revelation_place TEXT,
    total_verses INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.quran_verses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surah INTEGER REFERENCES public.quran_surahs(id) NOT NULL,
    ayah INTEGER NOT NULL,
    text_arabic TEXT NOT NULL,
    text_transliteration TEXT,
    text_english TEXT,
    text_bangla TEXT,
    audio_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(surah, ayah)
);
CREATE TABLE IF NOT EXISTS public.quran_tafsir (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surah INTEGER REFERENCES public.quran_surahs(id) NOT NULL,
    ayah INTEGER REFERENCES public.quran_verses(id) NOT NULL,
    author TEXT DEFAULT 'Ibn Kathir',
    text TEXT NOT NULL,
    language TEXT DEFAULT 'en',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.user_streaks (
    user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    current_streak INTEGER DEFAULT 0,
    longest_streak INTEGER DEFAULT 0,
    last_activity_date DATE DEFAULT CURRENT_DATE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.quran_progress (
    user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    total_verses_completed INTEGER DEFAULT 0,
    last_read_surah INTEGER,
    last_read_ayah INTEGER,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.quran_practice_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_time TIMESTAMP WITH TIME ZONE,
    verses_practiced INTEGER DEFAULT 0,
    avg_accuracy_score NUMERIC(5, 2)
);
CREATE TABLE IF NOT EXISTS public.notification_subscriptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_used_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(endpoint)
);
CREATE TABLE IF NOT EXISTS public.notification_settings (
    user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    prayer_start BOOLEAN DEFAULT TRUE,
    prayer_ending BOOLEAN DEFAULT TRUE,
    dua_reminders BOOLEAN DEFAULT TRUE,
    timezone TEXT DEFAULT 'UTC',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.notification_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE
    SET NULL,
        notification_type TEXT,
        message TEXT,
        delivered BOOLEAN DEFAULT FALSE,
        sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.fiqh_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE
    SET NULL,
        query_text TEXT NOT NULL,
        timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Enable Row Level Security
ALTER TABLE public.quran_surahs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quran_verses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quran_tafsir ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quran_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quran_practice_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fiqh_queries ENABLE ROW LEVEL SECURITY;
-- RLS Policies
CREATE POLICY "Public read surahs" ON public.quran_surahs FOR
SELECT USING (true);
CREATE POLICY "Public read verses" ON public.quran_verses FOR
SELECT USING (true);
CREATE POLICY "Public read tafsir" ON public.quran_tafsir FOR
SELECT USING (true);
CREATE POLICY "User view own streaks" ON public.user_streaks FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "User update own streaks" ON public.user_streaks FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User view own progress" ON public.quran_progress FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "User update own progress" ON public.quran_progress FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User view own sessions" ON public.quran_practice_sessions FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "User create own sessions" ON public.quran_practice_sessions FOR
INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "User manage subscriptions" ON public.notification_subscriptions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User manage settings" ON public.notification_settings FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "User view logs" ON public.notification_logs FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "User view own queries" ON public.fiqh_queries FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "User insert own queries" ON public.fiqh_queries FOR
INSERT WITH CHECK (auth.uid() = user_id);
-- Permissions
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres,
    service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;