-- MIGRATION: 06_RECITATION_ATTEMPTS
-- Objective: Add missing recitation_attempts table for AI Feedback
-- Run in Supabase SQL Editor
CREATE TABLE IF NOT EXISTS public.recitation_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    surah INTEGER NOT NULL,
    ayah INTEGER NOT NULL,
    transcription TEXT,
    feedback JSONB,
    score INTEGER,
    audio_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
-- Enable RLS
ALTER TABLE public.recitation_attempts ENABLE ROW LEVEL SECURITY;
-- Policies
CREATE POLICY "Users can view own recitations" ON public.recitation_attempts FOR
SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own recitations" ON public.recitation_attempts FOR
INSERT WITH CHECK (auth.uid() = user_id);
-- Permissions
GRANT ALL ON public.recitation_attempts TO postgres,
    service_role,
    authenticated;