-- Migration: App Versions & Maintenance Logic
-- Purpose: Allow remote configuration for minimum version and maintenance mode
CREATE TABLE IF NOT EXISTS public.app_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform text NOT NULL CHECK (platform IN ('ios', 'android', 'web')),
    min_version text NOT NULL,
    -- e.g. "1.0.2"
    latest_version text NOT NULL,
    -- e.g. "1.1.0"
    maintenance_mode boolean DEFAULT false,
    maintenance_message text,
    update_url text,
    created_at timestamp with time zone DEFAULT now()
);
-- RLS: Public read access
ALTER TABLE public.app_versions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to app_versions" ON public.app_versions FOR
SELECT TO public USING (true);
-- Functions to compare versions (Semantic Versioning)
-- Note: This logic is usually handled on client-side, but good to have table structure ready.
-- Insert default values
INSERT INTO public.app_versions (
        platform,
        min_version,
        latest_version,
        maintenance_mode
    )
VALUES ('android', '1.0.0', '1.0.0', false),
    ('ios', '1.0.0', '1.0.0', false) ON CONFLICT DO NOTHING;